import { motion } from 'motion/react';
import { HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const FAQS = [
  {
    question: "What is OmniAdapts and how does it work?",
    answer: "OmniAdapts is an AI-powered content adaptation tool that takes a single marketing message and transforms it into platform-specific copy for over 12 different social media channels. It uses advanced language models to understand the context of your message and apply the right tone, formatting, and length constraints for each platform."
  },
  {
    question: "Which social media platforms do you support?",
    answer: "We support all major platforms including Twitter (X), LinkedIn, Instagram (Feed & Stories), TikTok, Facebook, Pinterest, Reddit, YouTube, Discord, Telegram, and even Email Newsletters. You can also provide custom URLs for tailored website copy."
  },
  {
    question: "Is the content generated by OmniAdapts SEO-friendly?",
    answer: "Yes! For platforms like YouTube, Pinterest, and Quora, OmniAdapts specifically focuses on SEO-optimized descriptions, keywords, and tags to help your content rank better in search results."
  },
  {
    question: "Can I customize the tone of the generated copy?",
    answer: "While the tool automatically selects the most effective tone for each platform (e.g., professional for LinkedIn, witty for Twitter), you can influence the output by providing specific keywords or emotional benefits in the core message configuration."
  },
  {
    question: "Do I need a separate subscription for each platform?",
    answer: "No, one subscription gives you access to all supported platforms. You can generate copy for as many platforms as you need in a single click."
  },
  {
    question: "How do I get started with OmniAdapts?",
    answer: "Simply head over to our 'Tool' page, enter your product name and a brief description, select your target platforms, and click 'Generate Copy'. It's that easy!"
  }
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 bg-grid pointer-events-none" />
      
      <div className="max-w-4xl mx-auto px-4 relative z-10">
        <div className="text-center mb-24 space-y-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-secondary/5 border border-secondary/10 text-[10px] font-black text-secondary uppercase tracking-[0.2em]"
          >
            <HelpCircle className="w-3 h-3 text-secondary" />
            Support Center
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-6xl md:text-8xl font-black text-secondary tracking-tighter leading-[0.9]"
          >
            Frequently Asked <br />
            <span className="text-secondary/40">Questions</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-xl text-secondary/60 leading-relaxed font-medium max-w-2xl mx-auto"
          >
            Everything you need to know about OmniAdapts and how it can transform your social media strategy.
          </motion.p>
        </div>

        <div className="space-y-6">
          {FAQS.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className={cn(
                "border rounded-[3rem] transition-all duration-500 overflow-hidden group",
                openIndex === index ? "border-secondary bg-neutral shadow-2xl" : "border-secondary/10 bg-neutral/50 hover:border-secondary/20"
              )}
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full px-10 py-8 flex items-center justify-between text-left"
              >
                <span className={cn(
                  "font-black text-xl tracking-tight uppercase transition-colors duration-500",
                  openIndex === index ? "text-secondary" : "text-secondary/60 group-hover:text-secondary"
                )}>
                  {faq.question}
                </span>
                <div className={cn(
                  "w-10 h-10 rounded-full flex items-center justify-center border transition-all duration-500",
                  openIndex === index ? "bg-secondary border-secondary rotate-180" : "bg-secondary/5 border-secondary/10"
                )}>
                  <ChevronDown className={cn(
                    "w-5 h-5 transition-colors duration-500",
                    openIndex === index ? "text-neutral" : "text-secondary/40"
                  )} />
                </div>
              </button>
              <div
                className={cn(
                  "px-10 transition-all duration-500 ease-in-out",
                  openIndex === index ? "pb-10 max-h-96 opacity-100" : "max-h-0 opacity-0"
                )}
              >
                <p className="text-secondary/60 leading-relaxed font-medium text-lg border-t border-secondary/5 pt-6">
                  {faq.answer}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* SEO Structured Data */}
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": FAQS.map(faq => ({
            "@type": "Question",
            "name": faq.question,
            "acceptedAnswer": {
              "@type": "Answer",
              "text": faq.answer
            }
          }))
        })}
      </script>
    </div>
  );
}
